[package]
name = "ifmnb/array-buffer"
description = "Array object based on buffer"
version = "2609.1.0"
license = "GNU General Public License v3.0"
authors = ["Aftersky"]
repository = "https://github.com/IFMNB/luau-math"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["node_modules", "package.json", "**/*.ts"]

[dependencies]
BitMap = "ifmnb/bitmap@2609.1.3"